language: c
compiler:
    - clang
    - gcc
install:
    - sudo apt-get install -y libnet-dev
    - make
script: make test
notifications:
    irc: 'irc.freenode.org#thefox'
    on_success: never
    on_failure: always