language: c
compiler:
    - clang
    - gcc
before_install:
    - 'if [ "$CC" = "gcc" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi'
    - sudo apt-get update -qq
install:
    - sudo apt-get install -y libnet-dev
    - 'if [ "$CC" = "gcc" ]; then sudo apt-get install -qq gcc-4.8 g++-4.8; fi'
    - 'if [ "$CC" = "gcc" ]; then sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90; fi'
script: 'make && make test'