language: c
compiler:
    - clang
    - gcc
before_install:
    - sudo apt-get update
    - sudo apt-get install -y gcc-4.7
    - sudo apt-get install -y libnet-dev
    - libnet-config --defines
    - libnet-config --libs
    - libnet-config --cflags
script: 'make && make test'