language: c
compiler:
    - clang
    - gcc
before_install:
    - echo $CXX
    - echo $CC
    - sudo apt-get update
    - 'if [ "$CC" = "gcc" ]; then sudo apt-get install -y gcc-4.7; export CC="gcc-4.7"; fi'
    - sudo apt-get install -y libnet-dev
    - gcc --version
    - libnet-config --defines
    - libnet-config --libs
    - libnet-config --cflags
script: 'make && make test'